# Generated by Django 5.2.1 on 2025-06-17 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=255)),
                (
                    "event_type",
                    models.CharField(db_index=True, help_text="事件的类型", max_length=100),
                ),
                ("event_data", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="记录事件的用户",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="GameRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, help_text="该游戏轮次完成的日期和时间。"),
                ),
                ("original_image_url", models.TextField(help_text="用于本轮游戏的原始图片的URL。")),
                (
                    "player_prompt",
                    models.TextField(blank=True, help_text="人类玩家编写的提示词。", null=True),
                ),
                (
                    "player_generated_image_url",
                    models.TextField(
                        blank=True, help_text="由玩家提示词生成的图片的URL。", null=True
                    ),
                ),
                (
                    "player_similarity_score",
                    models.FloatField(
                        blank=True, help_text="玩家生成的图片与原图的相似度得分。", null=True
                    ),
                ),
                (
                    "ai_generated_prompt_from_image",
                    models.TextField(
                        blank=True, help_text="AI分析原始图片后生成的提示词。", null=True
                    ),
                ),
                (
                    "ai_generated_image_url",
                    models.TextField(
                        blank=True, help_text="由AI提示词生成的图片的URL。", null=True
                    ),
                ),
                (
                    "ai_similarity_score",
                    models.FloatField(
                        blank=True, help_text="AI生成的图片与原图的相似度得分。", null=True
                    ),
                ),
                (
                    "winner",
                    models.CharField(
                        blank=True,
                        choices=[("player", "玩家胜利"), ("ai", "AI胜利"), ("draw", "平局")],
                        db_index=True,
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="游戏的用户。",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_rounds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
