# Generated by Django 5.2.1 on 2025-06-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        db_index=True, help_text="用于标识用户单次访问或会话的标识符。", max_length=255
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, help_text="该游戏轮次完成的日期和时间。"),
                ),
                (
                    "original_image_url",
                    models.URLField(help_text="用于本轮游戏的原始图片的URL。", max_length=500),
                ),
                (
                    "player_prompt",
                    models.TextField(blank=True, help_text="人类玩家编写的提示词。", null=True),
                ),
                (
                    "player_generated_image_url",
                    models.URLField(
                        blank=True,
                        help_text="由玩家提示词生成的图片的URL。",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "player_similarity_score",
                    models.FloatField(
                        blank=True, help_text="玩家生成的图片与原图的相似度得分。", null=True
                    ),
                ),
                (
                    "ai_generated_prompt_from_image",
                    models.TextField(
                        blank=True, help_text="AI分析原始图片后生成的提示词。", null=True
                    ),
                ),
                (
                    "ai_generated_image_url",
                    models.URLField(
                        blank=True,
                        help_text="由AI提示词生成的图片的URL。",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "ai_similarity_score",
                    models.FloatField(
                        blank=True, help_text="AI生成的图片与原图的相似度得分。", null=True
                    ),
                ),
                (
                    "winner",
                    models.CharField(
                        blank=True,
                        choices=[("player", "玩家胜利"), ("ai", "AI胜利"), ("draw", "平局")],
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
