# Generated by Django 5.2.1 on 2025-06-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamecore", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameround",
            name="ai_generated_image_url",
            field=models.TextField(blank=True, help_text="由AI提示词生成的图片的URL。", null=True),
        ),
        migrations.AlterField(
            model_name="gameround",
            name="player_generated_image_url",
            field=models.TextField(blank=True, help_text="由玩家提示词生成的图片的URL。", null=True),
        ),
    ]
