# Generated by Django 5.2.1 on 2025-06-12 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamecore", "0002_alter_gameround_ai_generated_image_url_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gameround",
            name="session_id",
        ),
        migrations.AddField(
            model_name="gameround",
            name="user",
            field=models.ForeignKey(
                default=1,
                help_text="游戏的用户。",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_rounds",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
