# Generated by Django 5.2.1 on 2025-06-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamecore", "0004_alter_gameround_winner_gameevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameround",
            name="original_image_url",
            field=models.TextField(help_text="用于本轮游戏的原始图片的URL。"),
        ),
    ]
