# Generated by Django 5.2.1 on 2025-06-17 18:43

import gamecore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamecore", "0006_clean_long_image_urls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameround",
            name="original_image_url",
            field=models.ImageField(
                blank=True,
                help_text="用于本轮游戏的原始图片，上传后会自动重命名并保存。",
                max_length=500,
                null=True,
                upload_to=gamecore.models.game_image_upload_path,
            ),
        ),
    ]
