"""
Django settings for game_django project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv  # 导入 load_dotenv 用于加载 .env 文件
from urllib.parse import urlparse  # 导入 urlparse 用于解析URL

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 加载 .env 文件中的环境变量
load_dotenv(BASE_DIR / '.env')  # 显式指定路径更可靠

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# --- 从环境变量中安全地读取 SECRET_KEY ---
# getenv 的第二个参数是默认值，但对于 SECRET_KEY，我们希望在生产环境中如果未设置则直接报错
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("No SECRET_KEY set for Django application")

# --- 从环境变量中安全地读取 DEBUG 状态 ---
# os.getenv 返回的是字符串，所以需要和 'True' 进行比较
# 如果 .env 中没有定义 DEBUG，则默认为 False
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# --- 从环境变量中安全地读取 ALLOWED_HOSTS ---
# .env 文件中的值是 "domain.com,127.0.0.1"，我们需要将其解析成一个 Python 列表
PUBLIC_DOMAIN = os.getenv('PUBLIC_DOMAIN', 'http://127.0.0.1:8000')
allowed_hosts_str = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost')
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_str.split(',')]
# urlparse(PUBLIC_DOMAIN).hostname 会从 'https://your-domain.com' 中提取出 'your-domain.com'
parsed_public_domain = urlparse(PUBLIC_DOMAIN).hostname
if parsed_public_domain:
    ALLOWED_HOSTS.append(parsed_public_domain)

csrf_trusted_origins_str = os.getenv('CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_trusted_origins_str.split(',')] if csrf_trusted_origins_str else []


# Application definition

INSTALLED_APPS = [
    # django内置应用程序
    'django.contrib.admin',         # <--- Django 管理后台应用
    'django.contrib.auth',          # 认证框架
    'django.contrib.contenttypes',  # 内容类型框架 (被其他应用使用)
    'django.contrib.sessions',      # 会话框架
    'django.contrib.messages',      # 消息框架
    'django.contrib.staticfiles',   # 管理静态文件 (CSS, JavaScript, Images)
    'django.contrib.sites',  # dj-rest-auth/allauth 依赖的站点框架

    # 自定义应用程序
    'gamecore.apps.GamecoreConfig',  # gamecore应用配置

    # 第三方库
    'rest_framework',  # Django REST framework
    'rest_framework.authtoken',  # Django REST framework 的 token 认证
    'dj_rest_auth',  # Django REST framework 的认证和注册视图
    'dj_rest_auth.registration',  # Django REST framework 的注册视图
    'allauth',  # Django allauth 框架\
    'allauth.account',  # Django allauth 框架的账户应用
    'allauth.socialaccount',  # Django allauth 框架的社交账户应用
    'drf_spectacular',  # 用于生成 API 文档的工具

    # 跨域请求
    'corsheaders',
]

MIDDLEWARE = [
    # 跨域请求中间件
    "corsheaders.middleware.CorsMiddleware",

    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",  # 添加 allauth 中间件
]

ROOT_URLCONF = "game_django.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates']
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "game_django.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME'),             # 从环境变量读取
        'USER': os.getenv('DB_USER'),             # 从环境变量读取
        'PASSWORD': os.getenv('DB_PASSWORD'),       # 从环境变量读取
        'HOST': os.getenv('DB_HOST', 'localhost'),  # 从环境变量读取, 如果没有则默认为 'localhost'
        'PORT': os.getenv('DB_PORT', '3306'),     # 从环境变量读取, 如果没有则默认为 '3306'
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles' # 用于 collectstatic

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 配置媒体文件存储
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# --- django-allauth 配置 ---
SITE_ID = 1

# 允许使用用户名或邮箱登录
ACCOUNT_LOGIN_METHODS = {'email', 'username'}

# 明确要求在注册时必须提供邮箱和用户名
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']

# 在开发阶段，我们暂时关闭邮件验证流程
ACCOUNT_EMAIL_VERIFICATION = 'none'

# 配置 dj-rest-auth 认证方式为 token 认证
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    # 配置 API 文档生成工具
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# CORS 设置
# 明确允许的来源
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173", # 允许我们的 React 前端开发服务器访问
    "http://127.0.0.1:5173", # 有时 localhost 会被解析成 127.0.0.1，两个都加上更保险
]
# 允许凭证（如 Cookies）
CORS_ALLOW_CREDENTIALS = True

# drf-spectacular 设置
SPECTACULAR_SETTINGS = {
    'TITLE': 'Picture Talk API',
    'DESCRIPTION': 'API documentation for the Human vs AI picture talk game.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False, # 我们将在 URL 中自己处理 Schema

    # 这个设置强制 Swagger UI 从一个固定的、我们已知的路径加载 schema
    # 它解决了在反向代理后，UI 无法正确构建 schema URL 的问题
    'SWAGGER_UI_SETTINGS': {
    'url': '/api/schema/',
    },
}

